#:schema node_modules/wrangler/config-schema.json
name = "scheduling-api-rs"
main = "dist/scheduling_api/shim.mjs"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false

[[durable_objects.bindings]]
name = "scheduling_objects"
class_name = "SchedulingRepository"

[[migrations]]
tag = "v1"
new_classes = ["SchedulingRepository"]

[[queues.producers]]
binding = "scheduling_queue"
queue = "scheduling-rs-queue"

[[queues.producers]]
binding = "reservation_queue"
queue = "reservation-rs-queue"

[[queues.consumers]]
queue = "scheduling-rs-queue"

[[r2_buckets]]
binding = "scheduling_rs_bucket"
bucket_name = "scheduling-rs"